#include QMK_KEYBOARD_H
#include "keymap_german.h"


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

/*
void keyboard_post_init_user(void) {
    // Initialize RGB to static black
    rgblight_enable_noeeprom();
    rgblight_sethsv_noeeprom(HSV_BLACK);
    rgblight_mode_noeeprom(RGBLIGHT_MODE_STATIC_LIGHT);
}
void housekeeping_task_user(void) {
    switch (get_highest_layer(layer_state | default_layer_state)) {
        case 0:
            // Default layer
            rgblight_setrgb_at(RGB_BLACK, 0);
            break;
        case 4:
            rgblight_setrgb_at(RGB_GREEN, 0);
            break;
        case 2:
            rgblight_setrgb_at(100,100,1, 0);
            break;
        case 3:
            rgblight_setrgb_at(RGB_BLUE, 0);
            break;
    }
}*/

enum {
    TD_7_SLSH,
    TD_8_ASTR,
    TD_9_MINS,
    TD_6_PLUS,
    TD_3_EQL,
    TD_2_COMM,
};

tap_dance_action_t tap_dance_actions[] = {
    [TD_7_SLSH] = ACTION_TAP_DANCE_DOUBLE(KC_7, DE_SLSH),
    [TD_8_ASTR] = ACTION_TAP_DANCE_DOUBLE(KC_8, DE_ASTR),
    [TD_9_MINS] = ACTION_TAP_DANCE_DOUBLE(KC_9, DE_MINS),
    [TD_6_PLUS] = ACTION_TAP_DANCE_DOUBLE(KC_6, DE_PLUS),
    [TD_3_EQL] = ACTION_TAP_DANCE_DOUBLE(KC_3, DE_EQL),
    [TD_2_COMM] = ACTION_TAP_DANCE_DOUBLE(KC_2, DE_COMM),
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(
            KC_Q, LT(7,KC_W), LT(5, KC_F), KC_P, KC_B,
              KC_J, KC_L, LT(5, KC_U), LT(7, DE_Y), DE_UNDS,
            LALT_T(KC_A), LCTL_T(KC_R), LSFT_T(KC_S), LT(4,KC_T), KC_G,
              KC_M, LT(4,KC_N), LSFT_T(KC_E), LCTL_T(KC_I), LALT_T(KC_O),
            LT(8, DE_Z), KC_X, KC_C, LT(2, KC_D), KC_V,
              KC_K, KC_H, KC_COMM, KC_DOT, KC_AMPR,
            OSL(1), OSM(MOD_LSFT),
              KC_SPC, KC_BSPC),
	[1] = LAYOUT_split_3x5_2(
            DE_SS,          DE_UDIA,          DE_ODIA,          DE_ADIA, KC_NO,
              KC_NO, KC_TAB,         DE_LPRN,        DE_LCBR,        DE_LBRC,
            DE_TILD,        DE_HASH,        DE_PERC,        DE_COLN, KC_NO,
              KC_NO, KC_ESCAPE,      DE_LABK,        DE_DQUO,        DE_QUES,
            DE_BSLS,        DE_PIPE,        DE_AMPR,        DE_AT, KC_NO,
               KC_NO,DE_EURO,        DE_CIRC,        DE_ACUT,        DE_MINS,

            KC_NO, KC_NO, KC_ENTER,       KC_DELETE),
	[2] = LAYOUT_split_3x5_2(
            KC_NO,          LSFT(DE_UDIA),          LSFT(DE_ODIA),          LSFT(DE_ADIA), KC_NO,
              KC_NO, LSFT(KC_TAB),         DE_RPRN,        DE_RCBR,        DE_RBRC,
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
              KC_NO, KC_NO,      DE_RABK,        DE_QUOT,        DE_EXLM,
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
               KC_NO,KC_NO,        DE_DLR,        DE_GRV,        DE_PLUS,

            KC_NO, KC_NO, KC_ENTER,       KC_DELETE),
	[3] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, KC_TRNS, KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS, KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_BSLS, KC_GRV, KC_TRNS, RGB_RMOD, KC_TRNS, KC_TRNS, RGB_MOD),
	[4] = LAYOUT_split_3x5_2(
            KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
              KC_NO, KC_HOME,        KC_PGUP,        KC_PGDN,      KC_END,
            KC_NO, KC_LCTL,       KC_LSFT, KC_NO, KC_NO,
              KC_NO, KC_LEFT,        KC_UP,          KC_DOWN,        KC_RIGHT,
            KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO,
              KC_TRNS, LGUI(LSFT(KC_LEFT)),LGUI(KC_UP),    LGUI(KC_DOWN),  LGUI(LSFT(KC_RIGHT)),

            KC_VOLD, KC_TRNS, KC_TRNS, KC_VOLU),
	[5] = LAYOUT_split_3x5_2(
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
              KC_NO, TD(TD_7_SLSH), TD(TD_8_ASTR), TD(TD_9_MINS), DE_COLN,
            KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
              KC_TRNS, KC_4, KC_5, TD(TD_6_PLUS), DE_DOT,
            KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
              KC_NO, KC_1, TD(TD_2_COMM), TD(TD_3_EQL), KC_COMM,

            KC_TRNS, KC_TRNS,
            KC_TRNS, KC_TRNS
            ),
	[6] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_1, KC_2, KC_3, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_PAST, KC_4, KC_5, KC_6, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[7] = LAYOUT_split_3x5_2(
            KC_MEDIA_PREV_TRACK,KC_MEDIA_STOP,  KC_MEDIA_PLAY_PAUSE,KC_MEDIA_NEXT_TRACK, KC_NO,
              KC_NO, KC_MS_BTN1,     KC_MS_BTN3,     KC_MS_BTN2, KC_NO,
            KC_NO,  KC_AUDIO_MUTE,  KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP, KC_TRNS,
              KC_NO, KC_MS_LEFT,     KC_MS_UP,       KC_MS_DOWN,     KC_MS_RIGHT,
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
              KC_NO, KC_MS_ACCEL0,   KC_MS_WH_UP,    KC_MS_WH_DOWN, KC_NO,

            KC_MS_ACCEL2, KC_NO,
            KC_NO, KC_NO
            ),

	[8] = LAYOUT_split_3x5_2(
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
              KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
              KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
            KC_NO,        KC_NO,        KC_NO,        KC_NO, KC_NO,
              KC_NO,        KC_NO,        KC_NO,        KC_NO, QK_BOOT,

            KC_NO, KC_NO, KC_NO,       KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





